description "BatteryControl startup service"
INSTALL_DIR=$(cat /usr/local/bin/ChromeOS_PowerControl.install_dir)

start on started system-services
stop on runlevel [016]

respawn

exec "$INSTALL_DIR/batterycontrol __monitor__" >> /var/log/batterycontrol.log 2>&1
