#!/bin/bash
RED=$(tput setaf 1)
GREEN=$(tput setaf 2)
YELLOW=$(tput setaf 3)
BLUE=$(tput setaf 4)
MAGENTA=$(tput setaf 5)
CYAN=$(tput setaf 6)
BOLD=$(tput bold)
RESET=$(tput sgr0)
echo ""
echo ""
echo ""
echo "                                                        ${RED}████████████${RESET}           "
echo "                                                    ${RED}████${RESET}        ${RED}████${RESET}       "
echo "                                                  ${RED}██${RESET}              ${YELLOW}██${RESET}     "
echo "                                                ${GREEN}██${RESET}     ${BLUE}██████${RESET}     ${YELLOW}██${RESET}   "
echo "                                               ${GREEN}██${RESET}     ${BLUE}████████${RESET}     ${YELLOW}██${RESET}  "
echo "                                               ${GREEN}██${RESET}     ${BLUE}████████${RESET}     ${YELLOW}██${RESET}  "
echo "                                                ${GREEN}██${RESET}     ${BLUE}██████${RESET}     ${YELLOW}██${RESET}   "
echo "                                                  ${GREEN}██${RESET}              ${YELLOW}██${RESET}     "
echo "                                                    ${GREEN}████${RESET}        ${YELLOW}████${RESET}       "
echo "                                                        ${GREEN}████████████${RESET}           "
echo ""
echo "                                                   ${BOLD}${GREEN}Chrome${RESET}${BOLD}${RED}OS${RESET}${BOLD}${YELLOW}_${RESET}${BOLD}${BLUE}PowerControl${RESET}"
echo ""
echo ""
echo ""
echo "                                                       ${BOLD}Features:${RESET}"
echo "${CYAN}"
echo "╔═══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════╗"
echo "║  PowerControl: Control CPU clockspeed in relation to temperature; enabling lower temperatures under and longer battery life.  ║"
echo "╚═══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════╝"
echo "${RESET}${GREEN}"
echo "╔═══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════╗"
echo "║     BatteryControl: Control battery charging limit instead of relying on Adaptive Charging to maximize battery longevity.     ║"
echo "╚═══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════╝"
echo "${RESET}${YELLOW}"
echo "╔═══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════╗"
echo "║             FanControl: Control fan curve in relation to temperature with built-in hysteresis and 0% RPM mode.                ║"
echo "╚═══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════╝"
echo "${RESET}${MAGENTA}"
echo "╔═══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════╗"
echo "║      GPUControl: Control GPU clockspeed below its default maximum; enabling lower temperatures and longer battery life.       ║"
echo "╚═══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════╝"
echo "${RESET}${BLUE}"
echo "╔═══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════╗"
echo "║             SleepControl: Control how long ChromeOS can remain idle before sleep; with display dimming support.               ║"
echo "╚═══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════╝"
echo "${RESET}"
echo ""
echo ""
curl -L https://raw.githubusercontent.com/shadowed1/ChromeOS_PowerControl/unstable/ChromeOS_PowerControl_Installer.sh -o /home/chronos/ChromeOS_PowerControl_Installer.sh
echo "${CYAN}${BOLD}╔══════════════════════════════════════════════════════════════════════╗${RESET}"
echo "${GREEN}${BOLD}║  Downloading to: /home/chronos/ChromeOS_PowerControl_Installer.sh    ║${RESET}"
echo "${YELLOW}${BOLD}║  Run the installer with VT-2 or enable sudo in crosh.                ║${RESET}"
echo "${MAGENTA}${BOLD}║  Move it to an executable location or run these commands with VT-2:  ║${RESET}"
echo "${BLUE}${BOLD}╚══════════════════════════════════════════════════════════════════════╝${RESET}"
echo "${BOLD}"
echo "sudo mkdir -p /usr/local/bin"
echo ""
echo "sudo mv /home/chronos/ChromeOS_PowerControl_Installer.sh /usr/local/bin"
echo ""
echo "sudo bash /usr/local/bin/ChromeOS_PowerControl_Installer.sh"
echo "${RESET}"
echo ""
