description "FanControl startup service"

start on started system-services
stop on runlevel [016]

respawn

env INSTALL_DIR_FILE="/usr/local/bin/ChromeOS_PowerControl.install_dir"
env INSTALL_DIR=$(if [ -f "$INSTALL_DIR_FILE" ]; then cat "$INSTALL_DIR_FILE"; else echo "/usr/local/bin/ChromeOS_PowerControl"; fi)
exec $INSTALL_DIR/powercontrol __monitor__ >> var/log/fancontrol.log 2>&1
