start on started system-services
stop on runlevel [016]

respawn

INSTALL_DIR=$(cat /usr/local/bin/ChromeOS_PowerControl.install_dir)
exec "$INSTALL_DIR/powercontrol" __monitor__ >> /var/log/powercontrol.log 2>&1
